name: Expose Dotenv file as environment variables
description: ''
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

  repository: 
    description: The owner and repository name. For example, Codertocat/Hello-World
    default: ${{ github.repository }}
    required: false

  path: 
    description: The location of the dotenv file
    default: .env
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
